Added orders
firiatMoon/coffee_house pull request #1
Opened 2024-09-23 16:37 UTC by firiatMoon

2024-09-25 08:38 UTC, zor07 requested changes

2024-09-25 08:38 UTC, zor07 commented on src/main/java/com/capybara/coffee_house/exceptions/UnexpectedErrorResponse.java
> +    private int statusCode;
статус код в тело добавлять не обязательно, так как он в ответе и так возвращается

2024-09-25 08:38 UTC, zor07 commented on src/main/java/com/capybara/coffee_house/services/BonusCardService.java
> +        ClientBonusCardDto.ClientBonusCardDtoBuilder builder = ClientBonusCardDto.builder();
Билдер можно заинлайнить
```java
        ClientDto clientDto = Optional.ofNullable(bonusCard.getClient())
                .map(clientService::convertToDto)
                .orElse(new ClientDto(null, null,null,null,null,null,null));
        return ClientBonusCardDto.builder()
                .id(bonusCard.getId())
                .client(clientDto)
                .amount(bonusCard.getAmount())
                .discountPercent(bonusCard.getDiscountPercent())
                .build();
```

2024-09-25 08:38 UTC, zor07 commented on src/main/java/com/capybara/coffee_house/services/ClientBonusCardTransactionService.java
> +        ClientBonusCardTransaction.ClientBonusCardTransactionBuilder bonusCardTransactionBuilder =
Выносить билдер в отдельную переменную не обязательно, громоздкая конструкция усложняет чтение кода

2024-09-25 08:38 UTC, zor07 commented on src/main/java/com/capybara/coffee_house/services/ClientBonusCardTransactionService.java
> +                .build();
2 раза вызывается build. Можно убрать лишний, либо как-то так: 

```java
ClientBonusCardTransaction transaction = ClientBonusCardTransaction.builder()
                .order(order)
                .transactionType(transactionType)
                .points(points)
                .build();

clientBonusCardTransactionRepository.save(transaction);
```

2024-09-25 08:38 UTC, zor07 commented on src/main/java/com/capybara/coffee_house/services/ClientBonusCardTransactionService.java
> +        String message = order.getBonusPointsAction().equals(BonusPointsAction.USE)
Логика определения сообщения для уведомления клиента не должна быть в ответственности сервиса который отвечает за сохранение транзакции. Оставаясь тут `ClientBonusNotificationService `превращается просто в отправителя любого сообщения, а `ClientBonusCardTransactionService ` нарушает принцип SRP (single responsibility principal)

2024-09-25 08:38 UTC, zor07 commented on src/main/java/com/capybara/coffee_house/services/OrderService.java
> +                .build();
Или я не понимаю как билдер работает или 2 раза вызывать build кажется лишним) 
Писал про аналогичные ситуации выше

2024-09-25 08:38 UTC, zor07 commented on src/main/java/com/capybara/coffee_house/services/OrderService.java
> +//        Order order = new Order();
Лишний закоментированный код

2024-09-27 16:36 UTC, firiatMoon commented on src/main/java/com/capybara/coffee_house/exceptions/UnexpectedErrorResponse.java
> +    private int statusCode;
Исправлено

2024-09-27 16:36 UTC, firiatMoon commented on src/main/java/com/capybara/coffee_house/services/BonusCardService.java
> +        ClientBonusCardDto.ClientBonusCardDtoBuilder builder = ClientBonusCardDto.builder();
Исправлено

2024-09-27 16:36 UTC, firiatMoon commented on src/main/java/com/capybara/coffee_house/services/ClientBonusCardTransactionService.java
> +        ClientBonusCardTransaction.ClientBonusCardTransactionBuilder bonusCardTransactionBuilder =
Исправлено

2024-09-27 16:36 UTC, firiatMoon commented on src/main/java/com/capybara/coffee_house/services/ClientBonusCardTransactionService.java
> +                .build();
Исправлено

2024-09-27 16:36 UTC, firiatMoon commented on src/main/java/com/capybara/coffee_house/services/ClientBonusCardTransactionService.java
> +        String message = order.getBonusPointsAction().equals(BonusPointsAction.USE)
Исправлено

2024-09-27 16:37 UTC, firiatMoon commented on src/main/java/com/capybara/coffee_house/services/OrderService.java
> +                .build();
Исправлено

2024-09-27 16:37 UTC, firiatMoon commented on src/main/java/com/capybara/coffee_house/services/OrderService.java
> +//        Order order = new Order();
Исправлено

2024-09-27 18:44 UTC, zor07 approved these changes
Все хорошо, можно мерджить 👍

2024-09-28 07:50 UTC, merged